### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function WordPress\Plugin_Check\wp_normalize_path()

### ISSUE THREAD

**Issue by jcvignoli** [swissspidy/wp-plugin-check-action#68]
The workflow fails to run with the following message:
```
✔ Ran `wp plugin list-check-categories` in 'cli'. (in 0s 532ms)
ℹ Starting 'wp plugin check dist --format=json --exclude-directories=vendor,.wordpress-org --require=./wp-content/plugins/plugin-check/cli.php' on the cli container. 

[07-Apr-2024 13:33:54 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function WordPress\Plugin_Check\wp_normalize_path() in /var/www/html/wp-content/plugins/plugin-check/includes/Plugin_Context.php:45
Stack trace:
#0 /var/www/html/wp-content/plugins/plugin-check/cli.php(32): WordPress\Plugin_Check\Plugin_Context->__construct('/var/www/html/w...')
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(141): require_once('/var/www/html/w...')
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LoadRequiredCommand.php(56): WP_CLI\Utils\load_file('./wp-content/pl...')
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LoadRequiredCommand->process(Object(WP_CLI\Bootstrap\BootstrapState))
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#5 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('phar:///usr/loc...')
#6 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#7 {main}
  thrown in /var/www/html/wp-content/plugins/plugin-check/includes/Plugin_Context.php on line 45
✖ Command failed with exit code 255
Command failed with exit code 255

```
until three days ago, it wasn't throwing this error. My yml:
```
name: 'WP plugin check'
on:
  push:
    branches: "*"
  pull_request:
jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run plugin check
      uses: swissspidy/wp-plugin-check-action@v1
      with:
        build-dir: './dist'
        exclude-directories: 'vendor,.wordpress-org'

```
